name: Build Integrity Pipeline Test v1

on:
  push:
    branches:
      - 'test-build-integrity'
    paths:
      - 'test/integrity.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    #permissions:
      #contents: read
      #security-events: write
      #id-token: write
    steps:
      - name: Check out repo code
        uses: actions/checkout@v4
      
      - name: Run Scorecard Help to Test Functonality
        run: |
          docker run --rm ghcr.io/ossf/scorecard:latest --help
          echo "A new Repository source detected in integrity folder"
